#FROM debian:stable-slim
FROM registry.oxen.rocks/lokinet-base:latest
#$ARG DEBIAN_FRONTEND="noninteractive"

RUN apt update && \
  apt -y -qq --no-install-recommends install golang git
  #apt -y dist-upgrade \
#  && apt -y install build-essential cmake git libcap-dev pkg-config automake libtool libuv1-dev libsodium-dev libzmq3-dev libcurl4-openssl-dev libevent-dev nettle-dev libunbound-dev libsqlite3-dev libssl-dev libcap2-bin dialog golang screen

RUN go get -u github.com/majestrate/fedproxy \
  && cp /root/go/bin/fedproxy /usr/local/bin/

#RUN git clone --recursive https://github.com/oxen-io/lokinet && git checkout -b debian/bullseye
#WORKDIR /lokinet
#RUN mkdir build
#WORKDIR /lokinet/build

#RUN cmake .. -DBUILD_STATIC_DEPS=OFF -DBUILD_SHARED_LIBS=ON -DSTATIC_LINK=OFF
#RUN make -j$(nproc)

#WORKDIR /lokinet/build/daemon
#RUN chmod +x lokinet lokinet-bootstrap lokinet-vpn

#RUN apt update && \
#  apt -y -qq --no-install-recommends install curl gpg lsb-release && \
#  curl -so /etc/apt/trusted.gpg.d/oxen.gpg https://deb.oxen.io/pub.gpg && \
#	echo "deb https://deb.oxen.io $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/oxen.list && \
#	apt update && \
#	apt -y -qq install lokinet

#RUN apt update
#RUN apt -y -qq --no-install-recommends install curl gpg lsb-release ca-certificates
#RUN curl -so /etc/apt/trusted.gpg.d/oxen.gpg https://deb.oxen.io/pub.gpg
#RUN echo "deb https://deb.oxen.io $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/oxen.list
#RUN apt update
#RUN apt -y -qq install lokinet



#RUN mkdir /var/lib/lokinet
COPY lokinet.ini /var/lib/lokinet/lokinet.ini

#RUN /lokinet/build/daemon/lokinet-bootstrap

COPY start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

ENTRYPOINT ["/usr/local/bin/start.sh"]
